Add debugging lines

diff --git a/.github/workflows/check-code-directives.yml b/.github/workflows/check-code-directives.yml
--- a/.github/workflows/check-code-directives.yml
+++ b/.github/workflows/check-code-directives.yml
@@ -22,26 +22,28 @@ jobs:
             strings_to_search=('.. code-block::' '.. code::')
             errors=""  
             
-            # Get a list of changed files  
+            echo "Checking diff between origin/${{ github.base_ref }} and ${{ github.sha }}"  
+               
             changed_files=$(git diff --name-only origin/${{ github.base_ref }}...${{ github.sha }})  
+            echo "Changed files: $changed_files"  
               
-            for file in $changed_files; do  
-              # Extract new lines for each file, ignoring context lines and file headers  
+            for file in $changed_files; do      
+              echo "Checking file: $file"   
               new_lines=$(git diff origin/${{ github.base_ref }}...${{ github.sha }} -- "$file" | grep '^+' | grep -v '^\+\+\+')  
-      
-              # Check each string in new lines  
-              for search_string in "${strings_to_search[@]}"; do  
-                if echo "$new_lines" | grep -q "$search_string"; then  
-                  errors="$errors\nFile '$file' contains '$search_string'"  
-                fi  
-              done  
-            done
-      
-            if [ ! -z "$errors" ]; then  
-              echo -e "Errors found:\n$errors"
-              echo "Please replace these directives with '.. literalinclude::' or '.. io-code-block::'"
-              echo "For more information, refer to the wiki: [link here]"
-              exit 1  
-            else  
-              echo "No errors found."  
+              echo "New lines in $file: $new_lines"  
+            
+              for search_string in "${strings_to_search[@]}"; do      
+                if echo "$new_lines" | grep -q "$search_string"; then      
+                  errors="$errors\nFile '$file' contains '$search_string'"      
+                fi      
+              done      
+            done  
+          
+            if [ ! -z "$errors" ]; then      
+              echo -e "Errors found:\n$errors"  
+              echo "Please replace these directives with '.. literalinclude::' or '.. io-code-block::'"  
+              echo "For more information, refer to the wiki: [link here]"  
+              exit 1      
+            else      
+              echo "No errors found."      
             fi
